### ISSUE TITLE
mc fails with tag set

### ISSUE THREAD

**Issue by asitemade4u** [cboettig/minioclient#11] opened 2023-11-05 21:14 UTC
Hi,
And thank you for the package which is very useful!

I have an issue with `mc`.
- As there is no tag management functions in the package, I have to supplement some with `mc`
- So, I created a `mio_tag` function in R as:

```R
mio_tag <- function(thepth = "", thekey = "", theval = "") {
    if (stringr::str_length(thekey) > 2) {
        minioclient::mc(command = glue::glue('tag set {thepth} "{thekey}={theval}"'))
    }
}
```
I have followed the syntax of the native function in `mc`, `mc tag set`.
For example, with test values as:
```R
    thepth <- paste0(bkttst)
    thekey <- "tst"
    theval <- "test"
```
my function outputs this command in Minio's `mc`, which seems valid to me:
```bash
tag set mio/play-rcpgpefnjwks "tst=test"
```
- Of course, `mc` is appended when executing with your `mc` function.
- And I have tested for the presence of the key/value pair in the bucket.

Yet, I get this execution error:

```error
! System command 'mc' failed
---
Exit status: 1
Stderr:
mc: <ERROR> Failed to set tags for http://192.168.1.221:9000/play-rcpgpefnjwks. The TagKey you have provided is invalid.
```
What am I doing wrong?
S.

**Comment by cboettig** [comment] 2023-11-05 21:23
thanks for the bug report!  I'll take a look.

**Comment by cboettig** [comment] 2023-11-05 21:31
Can you try the dev version?  I think this was fixed in https://github.com/cboettig/minioclient/pull/7 but not yet released to CRAN.  (Will try and prep a CRAN release now!)

**Comment by cboettig** [comment] 2023-11-05 22:12
can you give me a reprex?  I see:

``` r
library(minioclient)

mc_mb("play/test-tag")
#> Bucket created successfully `play/test-tag`.
mc("tag set play/test-tag key=value", verbose = TRUE)
#> Tags set for https://play.min.io/test-tag.
```

<sup>Created on 2023-11-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16)
#>  os       Ubuntu 22.04.3 LTS
#>  system   x86_64, linux-gnu
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Etc/UTC
#>  date     2023-11-05
#>  pandoc   3.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [1] RSPM (R 4.3.0)
#>  digest        0.6.33  2023-07-07 [1] RSPM (R 4.3.0)
#>  evaluate      0.21    2023-05-05 [1] RSPM (R 4.3.0)
#>  fastmap       1.1.1   2023-02-24 [1] RSPM (R 4.3.0)
#>  fs            1.6.3   2023-07-20 [1] RSPM (R 4.3.0)
#>  glue          1.6.2   2022-02-24 [1] RSPM (R 4.3.0)
#>  htmltools     0.5.6   2023-08-10 [1] RSPM (R 4.3.0)
#>  knitr         1.44    2023-09-11 [1] RSPM (R 4.3.0)
#>  lifecycle     1.0.3   2022-10-07 [1] RSPM (R 4.3.0)
#>  minioclient * 0.0.6   2023-11-05 [1] local
#>  processx      3.8.2   2023-06-30 [1] RSPM (R 4.3.0)
#>  ps            1.7.5   2023-04-18 [1] RSPM (R 4.3.0)
#>  R6            2.5.1   2021-08-19 [1] RSPM (R 4.3.0)
#>  reprex        2.0.2   2022-08-17 [1] RSPM (R 4.3.0)
#>  rlang         1.1.1   2023-04-28 [1] RSPM (R 4.3.0)
#>  rmarkdown     2.25    2023-09-18 [1] RSPM (R 4.3.0)
#>  rstudioapi    0.15.0  2023-07-07 [1] RSPM (R 4.3.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] RSPM (R 4.3.0)
#>  withr         2.5.2   2023-10-30 [1] RSPM (R 4.3.0)
#>  xfun          0.40    2023-08-09 [1] RSPM (R 4.3.0)
#>  yaml          2.3.7   2023-01-23 [1] RSPM (R 4.3.0)
#> 
#>  [1] /usr/local/lib/R/site-library
#>  [2] /usr/local/lib/R/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by cboettig** [comment] 2023-11-05 23:03
@asitemade4u apologies I was unclear.  Can you 

a. Test my reprex above for you and let me know precisely what output you see.  As you see in my example above, that works for me. 

b. Can you please provide the output of sessionInfo() or sessioninfo::sessioninfo() so we know the version of the packages and operating system details you are running?  Again, you can see an example of my session info in my reprex above.  

c. You did the right thing to install the dev version from github. please confirm you also restarted your R session after doing that, otherwise you would still be running the old version.

d.  I did run the code you gave above without any issue.  Note that I modified it slightly, it really helps to use the `play` alias that ships with the minio client.  Technically your code above is not a "reprex" example because it implicitly assumes that the alias `mio` exists, which is not accurate.  However, it runs fine for me with the default test alias:

``` r
library(minioclient)
library(magrittr)
bkttst <- paste0(sample(letters, 12, replace = TRUE), collapse = "") %>%
  paste0("play/play-", .)
minioclient::mc_mb(bkttst, verbose = TRUE)
#> Bucket created successfully `play/play-njmnrivqubcx`.
system(command = "touch /tmp/test.csv")
minioclient::mc_cp("/tmp/test.csv", bkttst, recursive = TRUE, verbose = TRUE)
#> `/tmp/test.csv` -> `play/play-njmnrivqubcx/test.csv`
#> Total: 0 B, Transferred: 0 B, Speed: 0 B/s
thekey <- "tst"
theval <- "test"
minioclient::mc(command = glue::glue('tag set {bkttst}/test.csv "{thekey}={theval}"'))
```

<sup>Created on 2023-11-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Note the footer included by the reprex R package -- I know it's a bit pedantic but using the 'reprex' facility in R helps make sure you are sharing copy-paste examples that a developer can run.


I could reproduce your issue on the CRAN version, but it is resolved for me on the dev version, so I can only guess that perhaps you did not restart the R session and didn't get the dev version?  Do try the minimal example I sent above

```r
library(minioclient)

mc_mb("play/test-tag")
#> Bucket created successfully `play/test-tag`.
mc("tag set play/test-tag key=value", verbose = TRUE)
#> Tags set for https://play.min.io/test-tag.
```

and do tell me the sessionInfo() output.

**Comment by cboettig** [comment] 2023-11-06 00:07
All looks good.  Note in the failing reprex you still have version 0.0.5.

Please ensure you use the dev version, which should be 0.0.6


I think that should resolve the issue

**Comment by cboettig** [comment] 2023-11-06 03:05
no worries, we've all been there!  these things are so often more confusing than they look!  Learning tools like reprex & sessionInfo() do help a lot though!

**Closed by cboettig** 2023-11-06 03:05 UTC
